
include: package:flutter_lints/flutter.yaml

linter:
  rules:
        use_key_in_widget_constructors: false
        avoid_renaming_method_parameters: false
        use_build_context_synchronously: false
        curly_braces_in_flow_control_structures: false
        library_private_types_in_public_api: false

