name: paycool
description: Crypto payment application
version: 2.2.89+136

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependency_overrides:
  intl: any
  platform: ^3.1.0 #Error: Member not found: 'packageRoot'.

dependencies:
  auto_size_text: ^3.0.0
  #barcode_scan: null
  majascan:
  bitbox: ^0.0.1
  bitcoin_flutter: ^2.0.1
  bs58check: ^1.0.1
  #connectivity: ^0.4.3+1
  cupertino_icons: ^1.0.5
  decimal: ^2.2.0
  device_info: ^2.0.2
  encrypt: ^4.0.3
  flutter:
    sdk: flutter
  flutter_i18n: null
  flutter_localizations:
    sdk: flutter
  flutter_swiper: ^1.1.6
  flutter_treeview: ^1.0.7+1
  font_awesome_flutter: ^10.2.1
  image_picker:
  intl_translation: ^0.17.0
  keccak: ^1.0.3
  launch_review: ^3.0.1
  local_auth: ^2.1.3
  logger: ^1.1.0
  material_design_icons_flutter: ^6.0.7096
  observable_ish: null
  overlay_support: ^2.1.0
  package_info: ^2.0.2
  path_provider:
  protobuf: ^1.1.4
  #pull_to_refrsh: ^2.0.0
  qr_code_tools: ^0.0.7
  qr_flutter: ^4.0.0
  rflutter_alert: ^2.0.4
  screenshot: ^1.3.0
  share_plus: ^2.1.4
  shared_preferences: ^2.0.7
  shimmer: ^2.0.0
  sqflite: 
  stacked: ^2.1.6
  tree_view: ^0.0.5
  url_launcher: ^6.0.10
  version: ^3.0.2
  web3dart: null
  webview_flutter: ^3.0.4
  flutter_dotenv: 
  flutter_svg: ^0.19.2+1
  flutter_launcher_icons: ^0.8.1
  
dev_dependencies:
  flutter_lints: 
  flutter_test:
    sdk: flutter
  intl: ^0.17.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/start-page/
    - assets/images/img/
    - assets/images/flags/
    - assets/images/wallet-page/
    - assets/images/paycool/
    - assets/pages/index.html
    - assets/images/shared/
    - assets/images/club/
    - assets/images/launcher/
    - assets/i18n/
    - envs/

flutter_icons:
  image_path: "assets/images/launcher/paycool-logo-v1.jpg"
  android: true
  ios: true

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Thin.ttf
