name: paycool
description: Crypto payment application
version: 2.3.123+179
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.19.0 <3.0.0"

dependency_overrides:
  #intl: any
  convert: ^3.1.0
  bs58check: ^1.0.1
  hex: ^0.2.0
  #web3dart: 2.3.5
  # Could not resolve all artifacts for configuration ':image_picker_android:debugUnitTestRuntimeClasspath'
  image_picker_android: 0.8.4+13
  kyc:
    path: "../exchangily-packages/kyc"

dependencies:
  aukfa_version_checker:
    git:
      url: https://github.com/blockchaingate/exchangily-packages.git
      path: aukfa_version_checker
      ref: main
  auto_size_text: ^3.0.0
  bitbox:
    git:
      url: https://github.com/blockchaingate/exchangily-packages.git
      path: open_source_packages/bitbox_flutter
  bitcoin_flutter:
    git:
      url: https://github.com/blockchaingate/exchangily-packages.git
      path: open_source_packages/bitcoin_flutter
  cached_network_image: ^3.2.3
  card_swiper: null
  cupertino_icons: ^1.0.5
  decimal: ^2.2.0
  device_info: ^2.0.2
  encrypt: ^5.0.1
  exchangily_ui:
    git:
      url: https://github.com/blockchaingate/exchangily-packages.git
      path: exchangily_ui
      ref: main
  flutter:
    sdk: flutter
  flutter_dotenv: null
  flutter_i18n: null
  flutter_launcher_icons: null
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.0+1
  flutter_treeview: ^1.0.7+1
  font_awesome_flutter: ^10.2.1
  image_picker: ^0.8.6+1
  intl_translation: ^0.18.0
  keccak:
    git:
      url: https://github.com/blockchaingate/exchangily-packages.git
      path: open_source_packages/keccak

  kyc:
     git:
       url: https://github.com/blockchaingate/exchangily-packages.git
       path: kyc
       ref: main
  launch_review: ^3.0.1
  local_auth: ^2.1.3
  logger: ^1.1.0
  majascan: null
  material_design_icons_flutter: ^6.0.7096
  observable_ish: null
  overlay_support: ^2.1.0
  package_info: ^2.0.2
  path_provider: ^2.0.4
  protobuf: ^2.0.0
  qr_code_utils: ^0.0.1
  qr_flutter: ^4.0.0
  rflutter_alert: ^2.0.4
  screenshot: ^2.1.0
  share_plus: ^7.0.0
  shared_preferences: null
  shimmer: ^2.0.0
  sqflite: ^2.1.0+1
  stacked: ^3.1.0+3
  stacked_services: ^1.0.0
  tree_view: ^0.0.5
  upgrader: ^6.0.1
  url_launcher: ^6.0.10
  version: ^3.0.2
  web3dart: null
  webview_flutter: ^4.0.2

dev_dependencies:
  flutter_lints: null
  flutter_test:
    sdk: flutter
  intl:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/start-page/
    - assets/images/img/
    - assets/images/flags/
    - assets/images/wallet-page/
    - assets/images/paycool/
    - assets/pages/index.html
    - assets/images/shared/
    - assets/images/club/
    - assets/images/launcher/
    - assets/i18n/
    - envs/

flutter_icons:
  image_path: "assets/images/launcher/paycool-logo-v1.jpg"
  android: true
  ios: true

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Thin.ttf


