name: paycool
description: Crypto payment application
version: 2.2.52+92

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependency_overrides:
  intl: any

  # development purposes only

  exchangily_core:
    path: ../exchangily-packages/exchangily_core

  # exchangily_ui:
  #   path: ../exchangily-packages/exchangily_ui
       

  referral:
    path: ../exchangily-packages/referral
       

  lightning_remit:
    path: ../exchangily-packages/lightning_remit
       

  pagination_widget:
    path: ../exchangily-packages/pagination_widget
       

  exchangily_wallet_setup:
    path: ../exchangily-packages/exchangily_wallet_setup
         

  wallet_dashboard:
    path: ../exchangily-packages/wallet_dashboard
        

  exchangily_wallet_features:
    path: ../exchangily-packages/exchangily_wallet_features

dependencies:

  flutter:
    sdk: flutter
  flutter_i18n: null
  flutter_localizations:
    sdk: flutter

  flutter_swiper: ^1.1.6
  image_picker: 
  qr_code_tools: ^0.0.7
  qr_flutter: ^3.1.0

  observable_ish: null


  exchangily_core:
    git:
      url: ssh://git@github.com/blockchaingate/exchangily-packages.git
      path: exchangily_core
      ref: main 

  exchangily_ui:
    git:
      url: ssh://git@github.com/blockchaingate/exchangily-packages.git
      path: exchangily_ui
      ref: main 

  referral:
    git:
      url: ssh://git@github.com/blockchaingate/exchangily-packages.git
      path: referral
      ref: main 

  lightning_remit:
    git:
      url: ssh://git@github.com/blockchaingate/exchangily-packages.git
      path: lightning_remit
      ref: main 

  pagination_widget:
    git:
      url: ssh://git@github.com/blockchaingate/exchangily-packages.git
      path: pagination_widget
      ref: main 

  exchangily_wallet_setup:
    git:
      url: ssh://git@github.com/blockchaingate/exchangily-packages.git
      path: exchangily_wallet_setup
      ref: main   

  wallet_dashboard:
    git:
      url: ssh://git@github.com/blockchaingate/exchangily-packages.git
      path: wallet_dashboard
      ref: main  

  exchangily_wallet_features:
    git:
      url: ssh://git@github.com/blockchaingate/exchangily-packages.git
      path: exchangily_wallet_features
      ref: main    


       



dev_dependencies:
  flutter_launcher_icons: ^0.7.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  intl: ^0.17.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/start-page/
    - assets/images/img/
    - assets/images/wallet-page/
    - assets/images/paycool/
    - assets/pages/index.html
    - assets/images/shared/
    - assets/images/launcher/
    - assets/i18n/

flutter_icons:
  image_path: "assets/images/launcher/pay-cool-cube.jpg"
  android: true
  ios: true

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Thin.ttf
