import 'package:flutter/material.dart';

const Color primaryColor = Color(0xff3ecef3);
const Color secondaryColor = Color(0xff02193d);
const Color tertiaryColor = Color(0xff4285f4);
const Color walletCardColor = Color(0xff042144);
const Color iconBackgroundColor = Color.fromRGBO(83, 74, 223, 1);
const Color white = Colors.white;
const Color grey = Colors.grey;
const Color green = Colors.green;
const Color yellow = Colors.yellow;
const Color white38 = Colors.white38;
const Color white54 = Colors.white54;
const Color black = Colors.black;
const Color priceColor = Color(0xFF0da88b);
const Color sellOrders = Color(0xFF472a4a);
const Color sellPrice = Color(0xFFe2103c);
const Color buyOrders = Color(0xFF264559);
const Color buyPrice = Color(0xFF0da88b);
const Color red = Colors.red;
const Color exgLogoColor = Color.fromRGBO(207, 101, 68, .85);
const Color fabLogoColor = Color.fromRGBO(162, 48, 203, .85);
